/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_david_progresstaskbar_TaskBar */

#ifndef _Included_com_david_progresstaskbar_TaskBar
#define _Included_com_david_progresstaskbar_TaskBar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_david_progresstaskbar_TaskBar
 * Method:    setTaskbarProgress
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_david_progresstaskbar_TaskBar_setTaskbarProgress
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_david_progresstaskbar_TaskBar
 * Method:    setTaskbarProgressState
 * Signature: (Lcom/david/progresstaskbar/TaskBar/State;)V
 */
JNIEXPORT void JNICALL Java_com_david_progresstaskbar_TaskBar_setTaskbarProgressState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_david_progresstaskbar_TaskBar
 * Method:    getHWND
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_david_progresstaskbar_TaskBar_getHWND
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
